
server:
  port: 8001

spring:
  application:
    name: eureka-provider-8001

eureka:
  instance:
    hostname: eureka-provider-8001
    instance-id: eureka-provider-8001:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone : http://eureka-server-7001:7001/eureka/


info:
  app.name: eureka-provider-8001
  company.name: www.xiaowei.com
  build.artifactId: '@project.artifactId@'
  build.version: '@project.version@'


